#!/bin/bash

if [ -z $1 ] || [ -z $2 ]; then
    echo "No arguments provided"
    exit 1
fi

pauseforkey() {
    echo -n "Press any key to Reboot your system!"
    read -n 1 -s -r -p ""
    echo ""
}

# Variables
ID="$1"
ROOTPART="$2"
TEMPDIR="btrfsroot$ID"
# Display information
echo -e "Snapshot ID\t\t\t ===> $1"
echo -e "Root Partition\t\t\t ===> $2" 
echo -e "Temporary directory\t\t ===> /$TEMPDIR"
# Create temporary directory
sudo mkdir /$TEMPDIR
sudo mount -t btrfs -o subvolid=5 $ROOTPART /$TEMPDIR

# Change rollback-git config file
sudo sed -i "s/subvolid5 =.*/subvolid5 = \/$TEMPDIR/" /etc/rollback.conf

# Fire Rollback
sudo rollback $ID

# konsole --hide-menubar --hide-tabbar -e 
# Umount and delete temporary directory
sudo umount /$TEMPDIR
sudo rm -rf /$TEMPDIR
# Wait for user input
pauseforkey
reboot

