#!/bin/bash

ID="$1"
ROOTPART="$2"
NEWDIR="/btrfsroot$ID"
echo -e "Snapshot ID\t\t\t ===> $1"
echo -e "Root Partition\t\t\t ===> $2" 
echo -e "Temporary directory\t\t ===> $NEWDIR"
#sudo mkdir $NEWDIR


pauseforkey() {
    echo -n "Press any key to continue"
    read -n 1 -s -r -p ""
    echo ""
}


#sudo sed -i "s/subvolid5 =.*/subvolid = \/btrfs$1/" /etc/rollback.conf

# konsole --hide-menubar --hide-tabbar -e 

sudo rm -rf $NEWDIR

pauseforkey

