# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from rollback.api import FileUtil
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(953, 559)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f'{FileUtil.getResourcePath()}/images/xerolinux-logo128x128.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 90, 931, 401))
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSortIndicatorShown(False)
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(10, 0, 91, 91))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(f'{FileUtil.getResourcePath()}/images/xerolinux-logo96x96.png'))
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(110, 10, 711, 81))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(14)
        self.mainLabel.setFont(font)
        self.mainLabel.setTextFormat(QtCore.Qt.MarkdownText)
        self.mainLabel.setWordWrap(True)
        self.mainLabel.setObjectName("mainLabel")
        self.okPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.okPushButton.setGeometry(QtCore.QRect(620, 500, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Fira Code Medium")
        font.setPointSize(12)
        self.okPushButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(f'{FileUtil.getResourcePath()}/images/back-in-time.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okPushButton.setIcon(icon1)
        self.okPushButton.setIconSize(QtCore.QSize(32, 32))
        self.okPushButton.setObjectName("okPushButton")
        self.exitPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitPushButton.setGeometry(QtCore.QRect(790, 500, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Fira Code Medium")
        font.setPointSize(12)
        self.exitPushButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(f'{FileUtil.getResourcePath()}/images/exit.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitPushButton.setIcon(icon2)
        self.exitPushButton.setIconSize(QtCore.QSize(32, 32))
        self.exitPushButton.setObjectName("exitPushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Xerolinux Rollback Utility"))
        self.mainLabel.setText(_translate("MainWindow", "Please select the snapshot from the list below and click the rollback button."))
        self.okPushButton.setText(_translate("MainWindow", "&Rollback"))
        self.exitPushButton.setText(_translate("MainWindow", "&Exit"))
